services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: supersecret
      DB_NAME: postgres
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db_data:
